#!/bin/bash

set -e

function container {
  local version=$1
  host=$(ls ~/.virtualenvs/testrepository-$version-* -d | sed -e "s/^.*testrepository-$version-//")
  if [ -z "$host" ]; then
    echo "No host found for $version"
    return 1
  fi
  container=$host
  return 0
}

function start {
  local host=$1
  local state=$(sudo lxc-info -s -H -n $host)
  if [ "RUNNING" != "$state" ]; then
    sudo lxc-start -d -n $host
    sudo lxc-wait -n $host -s RUNNING -t 2
  fi
}

profile=$1
instance=$2
profile=2.7
instance=$1
shift 1
container $profile
files=
# accumulate files to copy
while [ "--" != "$1" ]; do
  files="$files $1"
  shift ;
done
shift # --
echo copying $files to node.
for f in $files; do
  rsync $f $host:$(dirname $f) ;
done
echo ssh to $host
ssh $host "cd $PWD && . ~/.virtualenvs/testrepository-$profile-$host/bin/activate && $@"

